# Specify the version of the Docker Compose.
version: "3.9"

# Define the services and applications that make up your application.
services:
  question-service:
    build: ./backend/question-service # Path to the directory containing the Dockerfile for building the question-service image.
    ports:
      - 5000:5000 # Maps port 3000 on the host to port 3000 in the container, making the app accessible on the host.
    volumes:
      - ./backend/question-service:/app # Mounts the host directory './demo-app' to '/app' in the container.
      - /app/node_modules # Anonymous Volume
    networks:
      - demo-network # Connects the demo-app to the 'demo-network' network.

  user-service:
    build: ./backend/user-service
    ports:
      - 5001:5001
    volumes:
      - ./backend/user-service:/app
      - /app/node_modules
    networks:
      - demo-network

networks:
  demo-network: # Defines a network named 'demo-network'.
    driver: bridge # Uses the bridge driver for the network, which is the default and most common network type in Docker.
